name: GenFeed

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  token: ${{ secrets.TOKEN }}
  repo: fzdwx.github.io

jobs:
  update-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
      - run: cd /tmp && git clone https://github.com/fzdwx/vitepress-blog-theme
      - run: cd /tmp/vitepress-blog-theme && go install .
      - run: cd /tmp && rm -rf vitepress-blog-theme
      - uses: actions/checkout@v3
      - run: bang version
      - run: bang feed
      - run: git config --global user.name "github.action"
      - run: git config --global user.email "action@github.com"
      - run: git add links.json
      - run: git commit -a -m "update"
      - run: git push
