name: SyncIssues
on:
  issues:
    types: [opened, edited, deleted, closed, locked, unlocked, labeled, pinned]
  issue_comment:
    types: [created, edited, deleted]
  # push:
  # branches:
  # - main

env:
  token: ${{ secrets.TOKEN }}
  repo: vitepress-blog-theme

jobs:
  update-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
      - run: cd /tmp && git clone https://github.com/fzdwx/vitepress-blog-theme
      - run: cd /tmp/vitepress-blog-theme && go install .
      - run: cd /tmp && rm -rf vitepress-blog-theme
      - uses: actions/checkout@v3
      - run: bang version
      - run: bang sync
      - run: git config --global user.name "github.action"
      - run: git config --global user.email "action@github.com"
      - run: git add .
      - run: git commit -a -m "update issue"
      - run: git push
